[package]
name = "justaprankbro"
version = "0.1.0"
authors = ["Markus Røyset <cosmicspacedragon@gmail.com>"]
edition = "2018"

[dependencies]
winit = "0.20.0-alpha3"

[dependencies.winapi]
version = "0.3.8"
features = ["errhandlingapi", "minwindef", "winerror", "winuser"]
